### DISCUSSION TITLE
How to add Azure service Connection string to Dapr Metadata?

### DISCUSSION THREAD

**Discussion by AMSDavis** [CommunityToolkit/Aspire#713] [Q&A]
I am working on a project where I have an Azure Cosmos DB that I want to use as a Dapr State store, however I'm attempting to leverage Aspire to stand up the Cosmos DB resource in Azure for individual developers.

The difficulty I'm running into is with configuring the Dapr state store to provide the URL to my (potentially newly deployed) Cosmos DB. The `WithMetadata` extension method appears to provide functionality similar to this, however as far as I can tell the metadata is getting written at build time and isn't getting replaced at run time with an actual connection string.

The code looks a bit like this:
```csharp
using CommunityToolkit.Aspire.Hosting.Dapr;
using Microsoft.Extensions.Hosting;

var builder = DistributedApplication.CreateBuilder(args);

var cosmos = builder.AddAzureCosmosDB("cosmos-db");

var db = cosmos.AddCosmosDatabase("datastore-db");
db.AddContainer("widgets", "/partitionKey"); // Must set partition key to "/partitionKey" for dapr - https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/#setup-azure-cosmosdb

var daprStateStore = builder.AddDaprStateStore("my-statestore",
    new DaprComponentOptions { LocalPath = "../MyDemoProject/.dapr/components/cosmosdb-statestore.yaml" });

// This doesn't seem to work
daprStateStore.WithMetadata("url", cosmos.Resource.ConnectionStringExpression.ValueExpression);

builder.AddProject<Projects.MyDemoProject>("mydemoproject")
    .WithDaprSidecar()
    .WithReference(daprStateStore)
    .WithReference(cosmos)
    .WaitFor(cosmos);

builder.Build().Run();
```

And for reference here is what the cosmosdb-statestore.yaml file looks like:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  initTimeout: 5m
  metadata:
    # URL metadata to be filled in by .net aspire or during deployment.
    # - name: url
    #   value: https://<cosmosdb-name>.documents.azure.com:443/
    - name: database
      value: "datastore-db"
    - name: collection
      value: "widgets"
```

Quick Diagram:

MyDemoProject   -----> Dapr Sidecar ----> cosmosdb statestore component ---> CosmosDB running in Azure
