### ISSUE TITLE
Hosting.Ngrok support v2 configuration file with labels

### ISSUE THREAD

**Issue by programmation** [CommunityToolkit/Aspire#446]
### Related to an existing integration?

Yes

### Existing integration

Ngrok

### Overview

A while back, ngrok allowed 1 fixed URL per free account, but it appears that the way to set it up involves using an edge, which is configured in my (v2) ngrok file like this:

```
version: 2
authtoken: <auth_toke>
tunnels:
  api:
    labels:
      - edge=<edge_id>
    addr: host.docker.internal:<port>
```

Since this version only supports v3 ngrok files I can't find a way to add the edge label.

### Usage example

```
var ngrok = builder.AddNgrok("ngrok")
    .WithAuthToken(ngrokToken)
    .WithTunnelEndpoint(api, "https", "custom-url", new Dictionary<string, string>() { ["key"] = "value" });
```

### Breaking change?

No

### Alternatives

No alternatives possible.

### Help us help you

Yes, I'd like to be assigned to work on this item
