### ISSUE TITLE
Define Dapr Component Schema Model & WithMetadata Extension Method

### ISSUE THREAD

**Issue by FullStackChef** [CommunityToolkit/Aspire#459]
### Related to an existing integration?

Yes

### Existing integration

Hosting.Dapr

### Overview

Define strongly typed C# model that reflects the generic Dapr component schema. This model will serve as the baseline for all Dapr component configurations, capturing common properties such as name, type, and metadata. In addition, we want to enhance the resource builder API by adding a WithMetadata extension method for IResourceBuilder<IDaprComponentResource>. This extension should allow runtime overwriting of metadata properties whether we are loading an existing YAML component file or creating a new component dynamically.

Additionally currently StateStore & PubSub components look for a matching yaml file in dapr default location and then fall back to inmemory versions
We should enhance this to check for the existence of .dapr/components/ yaml file in the apphost directory

lastly we should create a secretstore.local.env when running app host to manage secrets

e.g apphost/.dapr/components/pubsub.yaml

### Usage example

given a pubsub.yaml in .dapr/components of 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: protocol
    value: amqp
  - name: hostname
    value: localhost
  - name: username
    value: guest
  - name: password
    value: guest
```
We should allow

```
var builder = DistributedApplication.CreateBuilder(args);

var rmq = builder.AddRabbitMQ("rabbitMQ")
                   .WithManagementPlugin()
                   .WithEndpoint("tcp", e => e.Port = 5672)
                   .WithEndpoint("management", e => e.Port = 15672);


var stateStore = builder.AddDaprStateStore("statestore");

var pubSub = builder.AddDaprPubSub("pubsub")
                           .WithMetadata("password", rmq.Resource.PasswordParameter)
                    .WaitFor(rmq);

builder.AddProject<Projects.CommunityToolkit_Aspire_Hosting_Dapr_ServiceA>("servicea")
       .WithReference(stateStore)
       .WithReference(pubSub)
       .WithDaprSidecar()
       .WaitFor(rmq);

builder.AddProject<Projects.CommunityToolkit_Aspire_Hosting_Dapr_ServiceB>("serviceb")
       .WithReference(pubSub)
       .WithDaprSidecar()
       .WaitFor(rmq);

// console app with no appPort (sender only)
builder.AddProject<Projects.CommunityToolkit_Aspire_Hosting_Dapr_ServiceC>("servicec")
       .WithReference(stateStore)
       .WithDaprSidecar();

builder.Build().Run();
```
where the resulting yaml will be 

```
apiVersion: dapr.io/v1alpha1
      kind: Component
      auth:
        secretStore: secretstore
      metadata:
        name: pubsub
        namespace: default
      spec:
        type: pubsub.rabbitmq
        version: v1
        metadata:
        - name: protocol
          value: amqp
        - name: hostname
          value: localhost
        - name: username
          value: guest
        - name: password
          value: guest
        - name: password
          secretKeyRef:
            name: rabbitMQ-password
            key: rabbitMQ-password
```

with secretstore:

```yaml
apiVersion: dapr.io/v1alpha1
      kind: Component
      metadata:
        name: secretstore
      spec:
        type: secretstores.local.env
        version: v1
        metadata: []
```

### Breaking change?

No

### Alternatives

NA

### Help us help you

Yes, I'd like to be assigned to work on this item
