### ISSUE TITLE
Dapr HTTPEndpoint not configurable

### ISSUE THREAD

**Issue by derchirurg** [CommunityToolkit/Aspire#660]
### Related to an existing integration?

Yes

### Overview

Currently it is not possible to configure a HTTPEndpoint resource for Dapr with Aspire.
The scheme of HTTPEndpoinr resource looks like the following [HTTPEndpoints-Schema](https://docs.dapr.io/reference/resource-specs/httpendpoints-schema/)
```yaml
apiVersion: dapr.io/v1alpha1
kind: HTTPEndpoint
metadata:
  name: <NAME>  
spec:
  baseUrl: <REPLACE-WITH-BASEURL> # Required. Use "http://" or "https://" prefix.
  headers: # Optional
  - name: <REPLACE-WITH-A-HEADER-NAME>
    value: <REPLACE-WITH-A-HEADER-VALUE>
  - name: <REPLACE-WITH-A-HEADER-NAME>
    secretKeyRef:
      name: <REPLACE-WITH-SECRET-NAME>
      key: <REPLACE-WITH-SECRET-KEY>
  clientTLS:
    rootCA:
      secretKeyRef:
        name: <REPLACE-WITH-SECRET-NAME>
        key: <REPLACE-WITH-SECRET-KEY>
    certificate:
      secretKeyRef:
        name: <REPLACE-WITH-SECRET-NAME>
        key: <REPLACE-WITH-SECRET-KEY>
    privateKey:
      secretKeyRef:
        name: <REPLACE-WITH-SECRET-NAME>
        key: <REPLACE-WITH-SECRET-KEY>
scopes: # Optional
  - <REPLACE-WITH-SCOPED-APPIDS>
auth: # Optional
  secretStore: <REPLACE-WITH-SECRETSTORE>

```

Currently it is just possible to use AddMetadata, which adds a metadata entry on spec. It is not possible to add entries on spec directly like "baseUrl".

### Usage example

Add entries directly on spec

### Breaking change?

No

### Alternatives

none

### Help us help you

No, just wanted to propose this
